// Golden values generated by the reference (ttfx) RNG for seed 42.
#include "testutil.h"
#include "utils/rng.h"

int main(void) {
    double expected_random[8] = {
        0.81430514512290986, 0.31882104006166112, 0.98389416817748876, 0.70113559813475557,
        0.79350448969172904, 0.58809846646755959, 0.12535244206274210, 0.60512244865717257,
    };
    Rng r = rng_seeded(42);
    for (int i = 0; i < 8; i++) {
        CHECK(rng_random(&r) == expected_random[i]);
    }

    int64_t expected_randint[10] = {-10, 39, 25, -34, 27, -24, 21, 37, -42, 1};
    r = rng_seeded(42);
    for (int i = 0; i < 10; i++) {
        CHECK_EQ_INT(rng_randint(&r, -50, 50), expected_randint[i]);
    }

    int64_t expected_shuffle[10] = {3, 9, 8, 6, 0, 7, 1, 4, 2, 5};
    int64_t v[10];
    for (int i = 0; i < 10; i++) {
        v[i] = i;
    }
    r = rng_seeded(42);
    rng_shuffle(&r, v, 10, sizeof(int64_t));
    for (int i = 0; i < 10; i++) {
        CHECK_EQ_INT(v[i], expected_shuffle[i]);
    }

    double expected_uniform[5] = {
        1.75722058049163943, -0.22471583975335552, 2.43557667270995504, 1.30454239253902227,
        1.67401795876691617,
    };
    r = rng_seeded(42);
    for (int i = 0; i < 5; i++) {
        CHECK(rng_uniform(&r, -1.5, 2.5) == expected_uniform[i]);
    }

    return test_summary("test_rng");
}
